workspace:
  base: /go
  path: src/github.com/ecray/avdb

pipeline:
  test:
    image: golang:1.11
    commands:
      - go build -v
      - go test -cover $(go list ./... | grep -v /vendor/)
  
  build:
    image: golang:1.11
    debug: true
    commands:
      - make build-linux

  publish:
    image: plugins/docker
    repo: docker.marqeta.com/mq/devops/avdb
    registry: docker.marqeta.com
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG}
      - latest
    when:
      event: tag
