version: '3'

services:
  avdb:
    build:
      context: .
    image: avdb:latest
    depends_on:
    - db
    ports:
    - "3333:3333"
    links:
    - db
    depends_on:
    - db
    environment:
    - "AVDB_ADDR=0.0.0.0"
    - "AVDB_PORT=3333"
    - "DB_NAME=avdb"
    - "DB_USER=avdb"
    - "DB_PASS=avdb"
    - "DB_HOST=db"
    - "DB_PORT=5432"

  db:
    image: postgres:9.6-alpine
    expose:
    - 5432
    environment:
    #- "PGDATA=/var/lib/postgresql/data/pgdata"
    - "POSTGRES_DB=avdb"
    - "POSTGRES_USER=avdb"
    - "POSTGRES_PASSWORD=avdb"
