---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: avdb
  labels:
    app: postgres
spec:
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: postgres
  name: postgres
  namespace: avdb
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: avdb
        - name: POSTGRES_PASSWORD
          value: avdb
        - name: POSTGRES_USER
          value: avdb
        image: postgres:9.6-alpine
        name: postgres
        resources: {}
      restartPolicy: Always
status: {}
