apiVersion: v1
kind: Service
metadata:
  labels:
    app: avdb
  name: avdb
  namespace: avdb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  ports:
  - name: avdb
    port: 80
    targetPort: 3333
  selector:
    app: avdb
  type: LoadBalancer
status:
  loadBalancer: {}
