apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: avdb
  name: avdb
  namespace: avdb
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: avdb
    spec:
      containers:
      - name: avdb
        image: avdb:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3333
        env:
        - name: AVDB_ADDR
          value: 0.0.0.0
        - name: AVDB_PORT
          value: "3333"
        - name: DB_HOST
          value: postgres.avdb.svc.cluster.local
        - name: DB_NAME
          value: avdb
        - name: DB_PASS
          value: avdb
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: avdb
        resources: {}
      restartPolicy: Always
status: {}
