apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: avdb-app
  name: avdb-app
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: avdb-app
    spec:
      containers:
      - env:
        - name: AVDB_ADDR
          value: 0.0.0.0
        - name: AVDB_PORT
          value: "3333"
        - name: DB_HOST
          value: avdb-pgsql.default.svc.cluster.local
        - name: DB_NAME
          value: avdb
        - name: DB_PASS
          value: avdb
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: avdb
        image: my.docker-repo.com/avdb:latest
        name: avdb-app
        ports:
        - containerPort: 3333
        resources: {}
      restartPolicy: Always
status: {}
