apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: avdb-ing
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: avdb.example.local
    http:
      paths:
      - path: /
        backend:
          serviceName: avdb-svc
          servicePort: 3333
